// ─── Dummy Pakistani Matrimonial Data ────────────────────────────────────────

export const DUMMY_USERS: Record<string, any> = {
  "user-001": {
    id: "user-001", soulvera_id: "SV-1001", name: "Ahmed Hassan",
    email: "ahmed@example.com", phone: "03001234567",
    role: "individual", is_verified: true, is_active: true,
    created_at: "2024-03-01T10:00:00Z",
    profile: {
      user_id: "user-001", age: 28, gender: "Male",
      marital_status: "Never Married", height: "5'10\"", build: "Athletic",
      religion: "Islam", sect: "Sunni", religious_practice: "Practicing",
      caste: "Rajput", sub_caste: "Minhas", language: "Punjabi", city: "Lahore",
      relocate: "Yes", education: "Bachelor's in Computer Science",
      grade: "First Division", education_honors: null,
      islamic_education: "Madrassa Basics", profession: "Software Engineer",
      income: "80,000 - 1,20,000", father_occupation: "Government Officer",
      mother_occupation: "Housewife", brothers_count: 2, brothers_married: 1,
      sisters_count: 1, sisters_educated: true,
      family_description: "Respectable middle-class family from Lahore with strong family values.",
      houses_count: 1, house_location: "DHA Lahore", agricultural_land: false,
      plots: "1 Plot in DHA Phase 6", residence_address: "DHA Phase 5, Lahore",
      partner_min_age: 22, partner_max_age: 27, partner_height: "5'4\" - 5'7\"",
      partner_education: "At least Bachelor's", partner_profession: "Any respectable",
      partner_caste: "Open", partner_city: "Lahore preferred",
      partner_marital_status: "Never Married",
      about_me: "Software engineer with 5 years of experience. I love reading, travelling, and cricket. Looking for a compatible, educated, and family-oriented life partner.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03001234567", profile_complete: true,
    },
  },
  "user-002": {
    id: "user-002", soulvera_id: "SV-1002", name: "Muhammad Usman",
    email: "usman@example.com", phone: "03111234567",
    role: "individual", is_verified: true, is_active: true,
    created_at: "2024-03-05T10:00:00Z",
    profile: {
      user_id: "user-002", age: 30, gender: "Male",
      marital_status: "Never Married", height: "5'11\"", build: "Slim",
      religion: "Islam", sect: "Sunni", religious_practice: "Practicing",
      caste: "Syed", sub_caste: null, language: "Urdu", city: "Karachi",
      relocate: "Negotiable", education: "MBBS",
      grade: "First Division", education_honors: "Distinction in Medicine",
      islamic_education: null, profession: "Doctor",
      income: "2,00,000 - 3,00,000", father_occupation: "Retired Professor",
      mother_occupation: "Housewife", brothers_count: 1, brothers_married: 0,
      sisters_count: 2, sisters_educated: true,
      family_description: "Well-educated Syed family from Karachi.",
      houses_count: 2, house_location: "Clifton, Karachi", agricultural_land: false,
      plots: null, residence_address: "Clifton Block 4, Karachi",
      partner_min_age: 24, partner_max_age: 28, partner_height: "5'3\" - 5'7\"",
      partner_education: "At least Bachelor's", partner_profession: "Educated, any field",
      partner_caste: "Syed preferred", partner_city: "Karachi",
      partner_marital_status: "Never Married",
      about_me: "I am a doctor working at a private hospital. Family-oriented person who values religion, education, and mutual respect in a relationship.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03111234567", profile_complete: true,
    },
  },
  "user-003": {
    id: "user-003", soulvera_id: "SV-1003", name: "Ali Raza",
    email: "ali@example.com", phone: "03211234567",
    role: "individual", is_verified: true, is_active: true,
    created_at: "2024-03-08T10:00:00Z",
    profile: {
      user_id: "user-003", age: 27, gender: "Male",
      marital_status: "Never Married", height: "5'9\"", build: "Medium",
      religion: "Islam", sect: "Sunni", religious_practice: "Regular",
      caste: "Awan", sub_caste: null, language: "Punjabi", city: "Islamabad",
      relocate: "Yes", education: "MBA", grade: "First Division",
      education_honors: null, islamic_education: null, profession: "Accountant",
      income: "60,000 - 90,000", father_occupation: "Business",
      mother_occupation: "Housewife", brothers_count: 3, brothers_married: 2,
      sisters_count: 0, sisters_educated: false,
      family_description: "Conservative and religious family from Islamabad.",
      houses_count: 1, house_location: "F-10, Islamabad", agricultural_land: true,
      plots: "2 Plots in Islamabad", residence_address: "F-10/3, Islamabad",
      partner_min_age: 22, partner_max_age: 26, partner_height: "5'2\" - 5'6\"",
      partner_education: "Bachelor's minimum", partner_profession: "Teacher preferred",
      partner_caste: "Awan or Open", partner_city: "Islamabad",
      partner_marital_status: "Never Married",
      about_me: "A simple, honest and hardworking person. I believe in family values and religious upbringing. Looking for a pious and family-oriented life partner.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03211234567", profile_complete: true,
    },
  },
  "user-004": {
    id: "user-004", soulvera_id: "SV-1004", name: "Hassan Bilal",
    email: "hassan@example.com", phone: "03451234567",
    role: "individual", is_verified: false, is_active: true,
    created_at: "2024-03-12T10:00:00Z",
    profile: {
      user_id: "user-004", age: 32, gender: "Male",
      marital_status: "Never Married", height: "5'8\"", build: "Heavy",
      religion: "Islam", sect: "Sunni", religious_practice: "Practicing",
      caste: "Khan", sub_caste: "Yousafzai", language: "Pashto", city: "Peshawar",
      relocate: "No", education: "M.Ed", grade: "Second Division",
      education_honors: null, islamic_education: "Hafiz-e-Quran",
      profession: "Teacher", income: "40,000 - 60,000",
      father_occupation: "Retired Army", mother_occupation: "Housewife",
      brothers_count: 4, brothers_married: 3, sisters_count: 2, sisters_educated: true,
      family_description: "Pakhtun family with military background and strong values.",
      houses_count: 1, house_location: "Peshawar", agricultural_land: true,
      plots: null, residence_address: "Hayatabad, Peshawar",
      partner_min_age: 24, partner_max_age: 30, partner_height: "5'0\" - 5'6\"",
      partner_education: "Matric minimum", partner_profession: "Housewife preferred",
      partner_caste: "Khan or Pakhtun", partner_city: "Peshawar preferred",
      partner_marital_status: "Never Married",
      about_me: "A teacher by profession, a Muslim by heart. I want a simple, religious life with a compatible partner who understands family responsibilities.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03451234567", profile_complete: true,
    },
  },
  "user-005": {
    id: "user-005", soulvera_id: "SV-1005", name: "Bilal Akbar",
    email: "bilal@example.com", phone: "03341234567",
    role: "family", is_verified: true, is_active: true,
    created_at: "2024-03-15T10:00:00Z",
    profile: {
      user_id: "user-005", age: 29, gender: "Male",
      marital_status: "Never Married", height: "5'10\"", build: "Athletic",
      religion: "Islam", sect: "Sunni", religious_practice: "Moderate",
      caste: "Chaudhry", sub_caste: null, language: "Punjabi", city: "Lahore",
      relocate: "Yes", education: "BBA",
      grade: "First Division", education_honors: null, islamic_education: null,
      profession: "Business Owner", income: "3,00,000+",
      father_occupation: "Businessman", mother_occupation: "Housewife",
      brothers_count: 1, brothers_married: 1, sisters_count: 2, sisters_educated: true,
      family_description: "Affluent business family from Lahore. Modern thinking with Islamic values.",
      houses_count: 3, house_location: "Model Town, Lahore", agricultural_land: true,
      plots: "Multiple plots in Lahore", residence_address: "Model Town, Lahore",
      partner_min_age: 22, partner_max_age: 27, partner_height: "5'4\" - 5'8\"",
      partner_education: "Bachelor's minimum", partner_profession: "Any",
      partner_caste: "Open", partner_city: "Open",
      partner_marital_status: "Never Married",
      about_me: "Running a family business and looking to start a new chapter of life. I value respect, honesty, and a good family environment.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03341234567", profile_complete: true,
    },
  },
  "user-006": {
    id: "user-006", soulvera_id: "SV-2001", name: "Fatima Malik",
    email: "fatima@example.com", phone: "03001234568",
    role: "individual", is_verified: true, is_active: true,
    created_at: "2024-03-02T10:00:00Z",
    profile: {
      user_id: "user-006", age: 25, gender: "Female",
      marital_status: "Never Married", height: "5'4\"", build: "Slim",
      religion: "Islam", sect: "Sunni", religious_practice: "Practicing",
      caste: "Malik", sub_caste: null, language: "Punjabi", city: "Lahore",
      relocate: "Yes", education: "B.Ed",
      grade: "First Division", education_honors: null, islamic_education: "Hifdh",
      profession: "Teacher", income: "40,000 - 60,000",
      father_occupation: "Retired Government Officer",
      mother_occupation: "Housewife", brothers_count: 2, brothers_married: 1,
      sisters_count: 1, sisters_educated: true,
      family_description: "Respectable government-background family from Lahore with strong Islamic values.",
      houses_count: 1, house_location: "Johar Town, Lahore", agricultural_land: false,
      plots: null, residence_address: "Johar Town, Lahore",
      partner_min_age: 26, partner_max_age: 33, partner_height: "5'8\" - 6'0\"",
      partner_education: "Bachelor's minimum", partner_profession: "Stable income",
      partner_caste: "Open", partner_city: "Lahore preferred",
      partner_marital_status: "Never Married",
      about_me: "A dedicated teacher and a practicing Muslim. I enjoy reading Quran, cooking, and spending time with family. Looking for a pious, caring, and responsible life partner.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03001234568", profile_complete: true,
    },
  },
  "user-007": {
    id: "user-007", soulvera_id: "SV-2002", name: "Aisha Siddiqui",
    email: "aisha@example.com", phone: "03111234568",
    role: "individual", is_verified: true, is_active: true,
    created_at: "2024-03-06T10:00:00Z",
    profile: {
      user_id: "user-007", age: 27, gender: "Female",
      marital_status: "Never Married", height: "5'5\"", build: "Slim",
      religion: "Islam", sect: "Sunni", religious_practice: "Practicing",
      caste: "Siddiqui", sub_caste: null, language: "Urdu", city: "Karachi",
      relocate: "Negotiable", education: "MBBS",
      grade: "First Division", education_honors: "Gold Medalist",
      islamic_education: null, profession: "Doctor",
      income: "1,50,000 - 2,50,000", father_occupation: "Engineer",
      mother_occupation: "Doctor", brothers_count: 1, brothers_married: 0,
      sisters_count: 1, sisters_educated: true,
      family_description: "Professional educated family from Karachi with modern Islamic values.",
      houses_count: 2, house_location: "Gulshan-e-Iqbal, Karachi", agricultural_land: false,
      plots: "1 Plot in DHA Karachi", residence_address: "Gulshan-e-Iqbal, Karachi",
      partner_min_age: 28, partner_max_age: 35, partner_height: "5'8\" - 6'1\"",
      partner_education: "Bachelor's or above", partner_profession: "Doctor or Engineer",
      partner_caste: "Siddiqui or Open", partner_city: "Karachi preferred",
      partner_marital_status: "Never Married",
      about_me: "A hardworking doctor with a passion for helping people. I value education, respect and family. Looking for a well-educated, family-oriented life partner.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03111234568", profile_complete: true,
    },
  },
  "user-008": {
    id: "user-008", soulvera_id: "SV-2003", name: "Zara Ahmed",
    email: "zara@example.com", phone: "03211234568",
    role: "individual", is_verified: false, is_active: true,
    created_at: "2024-03-10T10:00:00Z",
    profile: {
      user_id: "user-008", age: 24, gender: "Female",
      marital_status: "Never Married", height: "5'3\"", build: "Slim",
      religion: "Islam", sect: "Sunni", religious_practice: "Moderate",
      caste: "Sheikh", sub_caste: null, language: "Urdu", city: "Islamabad",
      relocate: "Yes", education: "BS Computer Science",
      grade: "First Division", education_honors: "Dean's List",
      islamic_education: null, profession: "Software Engineer",
      income: "70,000 - 1,00,000", father_occupation: "Retired Colonel",
      mother_occupation: "Teacher", brothers_count: 0, brothers_married: 0,
      sisters_count: 2, sisters_educated: true,
      family_description: "Army background family from Islamabad. Educated and open-minded.",
      houses_count: 1, house_location: "E-11, Islamabad", agricultural_land: false,
      plots: null, residence_address: "E-11, Islamabad",
      partner_min_age: 26, partner_max_age: 32, partner_height: "5'8\" - 6'0\"",
      partner_education: "Engineer or IT field", partner_profession: "Tech or Business",
      partner_caste: "Open", partner_city: "Islamabad or Lahore",
      partner_marital_status: "Never Married",
      about_me: "A tech-savvy girl who loves coding, travelling and photography. Looking for a modern yet religious life partner who respects a working woman.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03211234568", profile_complete: true,
    },
  },
  "user-009": {
    id: "user-009", soulvera_id: "SV-2004", name: "Maryam Khan",
    email: "maryam@example.com", phone: "03451234568",
    role: "individual", is_verified: true, is_active: true,
    created_at: "2024-03-14T10:00:00Z",
    profile: {
      user_id: "user-009", age: 26, gender: "Female",
      marital_status: "Never Married", height: "5'5\"", build: "Medium",
      religion: "Islam", sect: "Sunni", religious_practice: "Practicing",
      caste: "Khan", sub_caste: "Yousafzai", language: "Pashto", city: "Rawalpindi",
      relocate: "No", education: "PharmD",
      grade: "First Division", education_honors: null, islamic_education: "Hafiza",
      profession: "Pharmacist", income: "60,000 - 90,000",
      father_occupation: "Businessman", mother_occupation: "Housewife",
      brothers_count: 3, brothers_married: 2, sisters_count: 1, sisters_educated: true,
      family_description: "Traditional Pakhtun family with religious values and good standing.",
      houses_count: 1, house_location: "Rawalpindi", agricultural_land: true,
      plots: null, residence_address: "Satellite Town, Rawalpindi",
      partner_min_age: 28, partner_max_age: 35, partner_height: "5'9\" - 6'1\"",
      partner_education: "Bachelor's minimum", partner_profession: "Stable job",
      partner_caste: "Khan preferred", partner_city: "Rawalpindi or Islamabad",
      partner_marital_status: "Never Married",
      about_me: "Hafiza-e-Quran, pharmacist by profession. I believe in strong family bonds and Islamic lifestyle. Looking for a sincere and God-fearing life partner.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03451234568", profile_complete: true,
    },
  },
  "user-010": {
    id: "user-010", soulvera_id: "SV-2005", name: "Noor Hussain",
    email: "noor@example.com", phone: "03341234568",
    role: "family", is_verified: true, is_active: true,
    created_at: "2024-03-18T10:00:00Z",
    profile: {
      user_id: "user-010", age: 28, gender: "Female",
      marital_status: "Never Married", height: "5'6\"", build: "Medium",
      religion: "Islam", sect: "Shia", religious_practice: "Practicing",
      caste: "Hussain", sub_caste: null, language: "Urdu", city: "Lahore",
      relocate: "Negotiable", education: "Bachelor's in Nursing",
      grade: "First Division", education_honors: null, islamic_education: null,
      profession: "Nurse", income: "50,000 - 70,000",
      father_occupation: "Doctor", mother_occupation: "Nurse",
      brothers_count: 2, brothers_married: 2, sisters_count: 2, sisters_educated: true,
      family_description: "Medical background family from Lahore. Educated and caring environment.",
      houses_count: 1, house_location: "Gulberg, Lahore", agricultural_land: false,
      plots: null, residence_address: "Gulberg III, Lahore",
      partner_min_age: 28, partner_max_age: 36, partner_height: "5'8\" - 6'2\"",
      partner_education: "Bachelor's minimum", partner_profession: "Medical or any stable",
      partner_caste: "Open", partner_city: "Lahore",
      partner_marital_status: "Never Married",
      about_me: "A compassionate nurse passionate about patient care. I love cooking, gardening, and family gatherings. Looking for a kind, responsible partner who values family.",
      photo_url: "", photo_privacy: "public", gallery_urls: [],
      contact_number: "03341234568", profile_complete: true,
    },
  },
  "admin-001": {
    id: "admin-001", soulvera_id: "SV-ADMIN", name: "Soulvera Admin",
    email: "admin@soulvera.com", phone: "03009999999",
    role: "admin", is_verified: true, is_active: true,
    created_at: "2024-01-01T00:00:00Z",
    profile: null,
  },
};

export const DUMMY_PROPOSALS = [
  {
    id: "prop-001",
    sender_id: "user-001", receiver_id: "user-006",
    status: "accepted", admin_status: "pending",
    chat_enabled: true, payment_status: "paid",
    message: "Assalam-o-Alaikum, I reviewed your profile and found it very compatible. I would like to propose.",
    created_at: "2024-04-01T10:00:00Z",
    sender: { id: "user-001", soulvera_id: "SV-1001", name: "Ahmed Hassan", profile: { age: 28, city: "Lahore", photo_url: "" } },
    receiver: { id: "user-006", soulvera_id: "SV-2001", name: "Fatima Malik", profile: { age: 25, city: "Lahore", photo_url: "" } },
  },
  {
    id: "prop-002",
    sender_id: "user-002", receiver_id: "user-007",
    status: "pending", admin_status: "pending",
    chat_enabled: false, payment_status: "unpaid",
    message: "Assalam-o-Alaikum, I found your profile very impressive. Looking forward to your response.",
    created_at: "2024-04-05T10:00:00Z",
    sender: { id: "user-002", soulvera_id: "SV-1002", name: "Muhammad Usman", profile: { age: 30, city: "Karachi", photo_url: "" } },
    receiver: { id: "user-007", soulvera_id: "SV-2002", name: "Aisha Siddiqui", profile: { age: 27, city: "Karachi", photo_url: "" } },
  },
  {
    id: "prop-003",
    sender_id: "user-003", receiver_id: "user-008",
    status: "pending", admin_status: "pending",
    chat_enabled: false, payment_status: "unpaid",
    message: "Assalam-o-Alaikum. Please review my profile.",
    created_at: "2024-04-08T10:00:00Z",
    sender: { id: "user-003", soulvera_id: "SV-1003", name: "Ali Raza", profile: { age: 27, city: "Islamabad", photo_url: "" } },
    receiver: { id: "user-008", soulvera_id: "SV-2003", name: "Zara Ahmed", profile: { age: 24, city: "Islamabad", photo_url: "" } },
  },
  {
    id: "prop-004",
    sender_id: "user-004", receiver_id: "user-009",
    status: "rejected", admin_status: "rejected",
    chat_enabled: false, payment_status: "unpaid",
    message: "Assalam-o-Alaikum. I would like to connect.",
    created_at: "2024-04-10T10:00:00Z",
    sender: { id: "user-004", soulvera_id: "SV-1004", name: "Hassan Bilal", profile: { age: 32, city: "Peshawar", photo_url: "" } },
    receiver: { id: "user-009", soulvera_id: "SV-2004", name: "Maryam Khan", profile: { age: 26, city: "Rawalpindi", photo_url: "" } },
  },
  {
    id: "prop-005",
    sender_id: "user-005", receiver_id: "user-010",
    status: "pending", admin_status: "pending",
    chat_enabled: false, payment_status: "unpaid",
    message: "Assalam-o-Alaikum. Please consider my proposal.",
    created_at: "2024-04-12T10:00:00Z",
    sender: { id: "user-005", soulvera_id: "SV-1005", name: "Bilal Akbar", profile: { age: 29, city: "Lahore", photo_url: "" } },
    receiver: { id: "user-010", soulvera_id: "SV-2005", name: "Noor Hussain", profile: { age: 28, city: "Lahore", photo_url: "" } },
  },
];

export const DUMMY_MESSAGES: Record<string, any[]> = {
  "user-001": [
    { id: "msg-001", sender_id: "user-001", receiver_id: "user-006", content: "Assalam-o-Alaikum! Mashallah it is wonderful to connect with you.", created_at: "2024-04-02T10:00:00Z" },
    { id: "msg-002", sender_id: "user-006", receiver_id: "user-001", content: "Wa Alaikum Assalam! JazakAllah for reaching out.", created_at: "2024-04-02T10:05:00Z" },
    { id: "msg-003", sender_id: "user-001", receiver_id: "user-006", content: "I hope this is the beginning of something beautiful, inshallah.", created_at: "2024-04-02T10:10:00Z" },
    { id: "msg-004", sender_id: "user-006", receiver_id: "user-001", content: "Inshallah. I would like to know more about your family background.", created_at: "2024-04-02T10:15:00Z" },
    { id: "msg-005", sender_id: "user-001", receiver_id: "user-006", content: "Of course! My family is from Lahore. My father is a retired government officer and we have strong family values.", created_at: "2024-04-02T10:20:00Z" },
  ],
};

export const DUMMY_NOTIFICATIONS = [
  { id: "notif-001", message: "Ahmed Hassan sent you a matrimonial proposal.", read: false, created_at: "2024-04-01T10:00:00Z", type: "proposal_received" },
  { id: "notif-002", message: "Your proposal to Ali Raza is awaiting review.", read: true, created_at: "2024-04-03T09:00:00Z", type: "proposal_sent" },
  { id: "notif-003", message: "Ahmed Hassan accepted your proposal! You can now chat.", read: false, created_at: "2024-04-02T11:00:00Z", type: "proposal_accepted" },
];

// Helper: get user by token
export function getUserFromToken(token: string | null): any {
  if (!token) return null;
  if (token.includes("admin")) return { ...DUMMY_USERS["admin-001"] };
  // Default logged-in user: Fatima (female, sees male profiles)
  return { ...DUMMY_USERS["user-006"], profileData: DUMMY_USERS["user-006"].profile, profileCreated: true, isShortlisted: false };
}

// All non-admin users as array
export const ALL_USERS_ARRAY = Object.values(DUMMY_USERS).filter((u) => u.role !== "admin");

// All male profiles (for female user to see in search)
export const MALE_PROFILES = ALL_USERS_ARRAY.filter((u) => u.profile?.gender === "Male");

// All female profiles
export const FEMALE_PROFILES = ALL_USERS_ARRAY.filter((u) => u.profile?.gender === "Female");
